Repository Ureca-Final-Project-Team1/UFO-Fi-BE, pull requests merged in 2025-07, with the labels that each got.

#24 UF-108 add fcm sendmessage
  src/main/java/com/example/ufo_fi/domain/notification/config/FirebaseConfig.java
  src/main/java/com/example/ufo_fi/domain/notification/controller/FcmTokenController.java
  src/main/java/com/example/ufo_fi/domain/notification/dto/request/FcmTokenSaveReq.java
  src/main/java/com/example/ufo_fi/domain/notification/dto/response/FcmTokenCommonRes.java
  src/main/java/com/example/ufo_fi/domain/notification/entity/FcmToken.java
  src/main/java/com/example/ufo_fi/domain/notification/exception/NotificationErrorCode.java
  src/main/java/com/example/ufo_fi/domain/notification/repository/FcmTokenRepository.java
  src/main/java/com/example/ufo_fi/domain/notification/service/FcmTokenService.java
  src/main/java/com/example/ufo_fi/domain/notification/service/NotificationService.java
  src/test/java/com/example/ufo_fi/UfoFiApplicationTests.java
  src/test/java/com/example/ufo_fi/config/TestFirebaseConfig.java
Labels: ✨feature

#29 UF-121 feat: firebase key 추가
  .github/workflows/cd.yml
Labels: ✨feature

#31 UF-125 fix: 볼륨 바인딩
  .github/workflows/cd.yml
Labels: ✨feature

#33 UF-127 fix: 파일 경로 분기 수정
  src/main/java/com/example/ufo_fi/domain/notification/config/FirebaseConfig.java
Labels: 🕷bug

#27 UF-120 add swagger
  build.gradle
  src/main/java/com/example/ufo_fi/domain/tradepost/controller/TradePostController.java
  src/main/java/com/example/ufo_fi/domain/tradepost/dto/request/TradePostCreateReq.java
  src/main/java/com/example/ufo_fi/global/config/SwaggerConfig.java
Labels: ✨feature

#50 UF-146 마이페이지 알림 설정 API
  src/main/java/com/example/ufo_fi/domain/notification/controller/FcmTokenController.java
  src/main/java/com/example/ufo_fi/domain/notification/controller/NotificationSettingController.java
  src/main/java/com/example/ufo_fi/domain/notification/controller/api/FcmTokenApiSpec.java
  src/main/java/com/example/ufo_fi/domain/notification/controller/api/NotificationSettingApiSpec.java
  src/main/java/com/example/ufo_fi/domain/notification/dto/request/FcmTokenSaveReq.java
  src/main/java/com/example/ufo_fi/domain/notification/dto/response/NotificationSettingReadRes.java
  src/main/java/com/example/ufo_fi/domain/notification/entity/Notification.java
  src/main/java/com/example/ufo_fi/domain/notification/entity/NotificationSetting.java
  src/main/java/com/example/ufo_fi/domain/notification/entity/NotificationType.java
  src/main/java/com/example/ufo_fi/domain/notification/exception/NotificationErrorCode.java
  src/main/java/com/example/ufo_fi/domain/notification/repository/NotificationRepository.java
  src/main/java/com/example/ufo_fi/domain/notification/service/NotificationSettingService.java
  src/main/java/com/example/ufo_fi/domain/signup/service/SignupService.java
  src/main/resources/application.yml
Labels: ✨feature

#53 UF-149 관심 상품 등록 API
  src/main/java/com/example/ufo_fi/domain/notification/common/InterestedCarriers.java
  src/main/java/com/example/ufo_fi/domain/notification/controller/InterestedPostApiSpec.java
  src/main/java/com/example/ufo_fi/domain/notification/controller/InterestedPostController.java
  src/main/java/com/example/ufo_fi/domain/notification/dto/request/InterestedPostUpdateReq.java
  src/main/java/com/example/ufo_fi/domain/notification/entity/InterestedPost.java
  src/main/java/com/example/ufo_fi/domain/notification/exception/NotificationErrorCode.java
  src/main/java/com/example/ufo_fi/domain/notification/repository/InterestedPostRepository.java
  src/main/java/com/example/ufo_fi/domain/notification/service/InterestedPostService.java
Labels: ✨feature

#69 UF-174 거래 완료 및 관심 상품 등록 이벤트 발행
  src/main/java/com/example/ufo_fi/domain/notification/listener/AccountSuspendEventListener.java
  src/main/java/com/example/ufo_fi/domain/notification/processor/CreatedPostNotificationProcessor.java
  src/main/java/com/example/ufo_fi/domain/tradepost/service/TradePostService.java
  src/main/java/com/example/ufo_fi/domain/user/entity/UserPlan.java
  src/main/java/com/example/ufo_fi/global/config/WebConfig.java
Labels: ✨feature

#72 UF-177 Swagger 배포 url 추가
  src/main/java/com/example/ufo_fi/global/config/SwaggerConfig.java
Labels: 🩹fix

#84 UF-194 일괄 구매로직 수정
  src/main/java/com/example/ufo_fi/domain/tradepost/dto/request/TradePostBulkPurchaseReq.java
  src/main/java/com/example/ufo_fi/domain/tradepost/entity/BulkPurchaseType.java
  src/main/java/com/example/ufo_fi/domain/tradepost/repository/TradePostQueryDslImpl.java
  src/main/java/com/example/ufo_fi/domain/tradepost/service/TradePostService.java
Labels: ✨feature

#93 UF-231 일괄 구매 조회 수정
  src/main/java/com/example/ufo_fi/domain/tradepost/dto/request/TradePostBulkPurchaseReq.java
  src/main/java/com/example/ufo_fi/domain/tradepost/entity/BulkPurchaseType.java
  src/main/java/com/example/ufo_fi/domain/tradepost/repository/TradePostQueryDslImpl.java
  src/main/java/com/example/ufo_fi/domain/tradepost/service/TradePostService.java
Labels: ✨feature

#91 UF-215 zet 충전을 위한 Payment Gateway 도입
  .gitignore
  src/main/java/com/example/ufo_fi/domain/payment/config/PaymentConfig.java
  src/main/java/com/example/ufo_fi/domain/payment/controller/PaymentController.java
  src/main/java/com/example/ufo_fi/domain/payment/controller/api/PaymentApiSpec.java
  src/main/java/com/example/ufo_fi/domain/payment/dto/request/ConfirmReq.java
  src/main/java/com/example/ufo_fi/domain/payment/dto/request/PaymentReq.java
  src/main/java/com/example/ufo_fi/domain/payment/dto/response/ConfirmRes.java
  src/main/java/com/example/ufo_fi/domain/payment/dto/response/PaymentRes.java
  src/main/java/com/example/ufo_fi/domain/payment/entity/Payment.java
  src/main/java/com/example/ufo_fi/domain/payment/entity/PaymentStatus.java
  src/main/java/com/example/ufo_fi/domain/payment/exception/PaymentErrorCode.java
  src/main/java/com/example/ufo_fi/domain/payment/repository/PaymentRepository.java
  src/main/java/com/example/ufo_fi/domain/payment/service/PaymentService.java
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: ✨feature

#95 UF-220 금칙어 기능 구현
  build.gradle
  src/main/java/com/example/ufo_fi/domain/bannedword/controller/BannedWordController.java
  src/main/java/com/example/ufo_fi/domain/bannedword/controller/api/BannedWordApiSpec.java
  src/main/java/com/example/ufo_fi/domain/bannedword/dto/request/BannedWordCreateReq.java
  src/main/java/com/example/ufo_fi/domain/bannedword/dto/request/BannedWordDeleteBulkReq.java
  src/main/java/com/example/ufo_fi/domain/bannedword/dto/request/BannedWordReadPageReq.java
  src/main/java/com/example/ufo_fi/domain/bannedword/dto/response/BannedWordBulkDeleteRes.java
  src/main/java/com/example/ufo_fi/domain/bannedword/dto/response/BannedWordCreateRes.java
  src/main/java/com/example/ufo_fi/domain/bannedword/dto/response/BannedWordDeleteRes.java
  src/main/java/com/example/ufo_fi/domain/bannedword/dto/response/BannedWordReadRes.java
  src/main/java/com/example/ufo_fi/domain/bannedword/entity/BannedWord.java
  src/main/java/com/example/ufo_fi/domain/bannedword/exception/BannedWordErrorCode.java
  src/main/java/com/example/ufo_fi/domain/bannedword/filter/BannedWordFilter.java
  src/main/java/com/example/ufo_fi/domain/bannedword/filter/FuzzyMatcher.java
  src/main/java/com/example/ufo_fi/domain/bannedword/filter/JamoUtil.java
  src/main/java/com/example/ufo_fi/domain/bannedword/filter/Preprocessor.java
  src/main/java/com/example/ufo_fi/domain/bannedword/repository/BannedWordRepository.java
  src/main/java/com/example/ufo_fi/domain/bannedword/service/BannedWordService.java
  src/main/java/com/example/ufo_fi/domain/bannedword/validator/BannedWordCommonValidator.java
  src/main/java/com/example/ufo_fi/domain/tradepost/service/TradePostService.java
Labels: ✨feature

#107 UF-262 통계 조회 API 추가
  src/main/java/com/example/ufo_fi/domain/statistics/StatisticsController.java
  src/main/java/com/example/ufo_fi/domain/statistics/StatisticsService.java
  src/main/java/com/example/ufo_fi/domain/statistics/api/StatisticsApiSpec.java
  src/main/java/com/example/ufo_fi/domain/statistics/dto/response/StatisticsReportsRes.java
  src/main/java/com/example/ufo_fi/domain/statistics/dto/response/StatisticsRes.java
  src/main/java/com/example/ufo_fi/domain/tradepost/repository/TradePostRepository.java
  src/main/java/com/example/ufo_fi/domain/user/repository/UserRepository.java
Labels: ✨feature

#109 UF-272 로그아웃 기능 추가
  src/main/java/com/example/ufo_fi/domain/signup/controller/LogoutController.java
  src/main/java/com/example/ufo_fi/domain/signup/controller/api/LogoutApiSpec.java
  src/main/java/com/example/ufo_fi/domain/signup/service/LogoutService.java
  src/main/java/com/example/ufo_fi/global/security/jwt/JwtUtil.java
Labels: ✨feature

#122 UF-292 알림 저장 및 조회
  src/main/java/com/example/ufo_fi/domain/notification/controller/NotificationController.java
  src/main/java/com/example/ufo_fi/domain/notification/controller/api/NotificationApiSpec.java
  src/main/java/com/example/ufo_fi/domain/notification/dto/response/NotificationListRes.java
  src/main/java/com/example/ufo_fi/domain/notification/dto/response/NotificationRes.java
  src/main/java/com/example/ufo_fi/domain/notification/entity/NotificationHistory.java
  src/main/java/com/example/ufo_fi/domain/notification/event/NotificationTemplate.java
  src/main/java/com/example/ufo_fi/domain/notification/processor/AccountSuspendNotificationProcessor.java
  src/main/java/com/example/ufo_fi/domain/notification/processor/BenefitNotificationProcessor.java
  src/main/java/com/example/ufo_fi/domain/notification/processor/CreatedPostNotificationProcessor.java
  src/main/java/com/example/ufo_fi/domain/notification/processor/TradeCompletedNotificationProcessor.java
  src/main/java/com/example/ufo_fi/domain/notification/repository/NotificationHistoryRepository.java
  src/main/java/com/example/ufo_fi/domain/notification/service/FcmService.java
  src/main/java/com/example/ufo_fi/domain/notification/service/NotificationService.java
  src/main/resources/application.yml
  src/test/resources/application-test.properties
  src/test/resources/application-test.yml
Labels: ✨feature

#124 UF-298 database 생성 및 쿠키 설정 변경
  src/main/java/com/example/ufo_fi/global/security/oauth/CookieUtil.java
  src/main/resources/application.yml
Labels: 🩹fix

#126 UF-299 hibernate 설정 변경
  src/main/resources/application.yml
Labels: 🩹fix
